import styled, { keyframes } from "styled-components";
import Logo from "../assets/techLab-logo.jpg";
import { IoCloseCircleSharp } from "react-icons/io5";

import { useState } from "react";
import SignInForm from "../components/Modal/SignInForm";
import SignUpForm from "../components/Modal/SignUpForm";

export default function Modal(props) {
  const [signUpShow, setSignUpShow] = useState(false);
  const setSignUpShowHandler = () => {
    setSignUpShow((signUpShow) => (signUpShow = !signUpShow));
  };

  return (
    <Wrapper>
      <ModalCard>
        <CloseButton onClick={props.modalHandler}>
          <IoCloseCircleSharp size={36} color={"white"} />
        </CloseButton>
        <LogoWrapper>
          <FormLogo src={Logo} />
        </LogoWrapper>

        {!signUpShow && <SignInForm signUpShowHandler={setSignUpShowHandler} />}
        {signUpShow && <SignUpForm signUpShowHandler={setSignUpShowHandler} />}
      </ModalCard>
    </Wrapper>
  );
}

const wrapperAnim = keyframes`
    /* ----------------------------------------------
    * Generated by Animista on 2022-11-18 19:44:13
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info. 
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */
    0% { 
    -webkit-backdrop-filter: blur(0px) saturate(100%); 
    }
    100% { 
    -webkit-backdrop-filter: blur(20px) saturate(100%); 
    }
`;

const Wrapper = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;

  z-index: 3;
  position: fixed;
  width: 100vw;
  height: 100vh;
  padding: 20px 0px;

  top: 0px;
  left: 0px;
  right: 0px;
  bottom: 0px;

  background-color: rgba(0, 0, 0, 0.2);
  -webkit-backdrop-filter: blur(20px) saturate(100%);
  backdrop-filter: blur(20px) saturate(100%);

  animation-delay: 0s;
  animation-duration: 2s;
  animation-name: ${wrapperAnim};
`;

const cardAnim = keyframes`
    0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
    }
    100% {
    -webkit-transform: scale(1);
            transform: scale(1);
    }
`;
const ModalCard = styled.div`
  display: grid;
  position: relative;
  justify-items: center;
  z-index: 3;
  grid-template-columns: 360px auto;
  gap: 20px;

  margin: 30px;
  max-width: 960px;
  width: 100%;
  border-radius: 20px;
  padding: 20px;

  background-color: rgba(50, 61, 109, 0.5);
  box-shadow: rgba(0, 0, 0, 0.25) 0px 50px 100px,
    rgba(255, 255, 255, 0.3) 0px 0px 0px 0.5px inset;
  animation-duration: 1s;
  animation-delay: 0s;
  animation-name: ${cardAnim};

  @media (max-width: 900px) {
    grid-template-columns: auto;
    gap: 20px;
  }
`;

const LogoWrapper = styled.div`
  display: grid;
  width: 100%;
  height: 100%;
  justify-content: center;
  align-content: center;

  border-radius: 20px;
  background-color: rgb(5, 125, 205);

  @media (max-width: 900px) {
    display: none;
  }
`;

const FormLogo = styled.img`
  max-width: 100%;
  /* max-height: 600px; */
  padding: 0;
  margin: 0;
  border-radius: 15px;

  /* @media (max-width: 900px) {
        max-height: 200px;
    } */
`;

const CloseButton = styled.div`
  position: absolute;
  top: -15px;
  right: -15px;
`;
